# -*- coding: utf-8 -*-
"""implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UgQX5pQSACsberCj-1ZiABN-Jhqgz9d4
"""

from google.colab import drive
drive.mount('/content/drive/')

import glob
files = glob.glob('/content/drive/MyDrive/data1/dataset/S01R01.txt')

files

import numpy as np
for f in files:
  data_array = np.empty((0, 11))
  with open(f, "r") as f:
    for line in f:
        lst = list(map(float, line.split(' ')))
        data_array = np.append(data_array, [lst[0:11]], axis = 0)
data_array

data_fg_complete = np.empty((0, 0, 10))
data_array_fg = np.empty((0, 10))

for l in range(0, np.shape(data_array)[0]):
  #print(l)
  #print(data_array[l,-1]);
  
  if data_array[l,-1] == 2:
        data_array_fg = np.append(data_array_fg, [data_array[l,0:10]], axis=0)
        if data_array[l+1,-1] == 1:
          data_fg_complete = np.append(data_fg_complete, [data_array_fg], axis=0)
          #interpolate
          #extrapolate
          #mean, median
  

print(data_fg_complete)

